### ISSUE TITLE
Dataset pre-processing

### ISSUE THREAD

**Issue by risk-v** [cschoeller/constant_velocity_pedestrian_motion#1]
Hi Christoph,

First of all, thanks for sharing your code. I was wondering, how did you generate the .json files in the folder ../data/eth_univ/data/. For instance, if we look inside the file "3.json" we get the next entry: {"timestamp": 80, "object_list": [{"position": [10.67, 3.99], "id": 1}, {"position": [13.64, 5.8], "id": 2}], "frame": 80, "size": 2} but the original dataset (obsmat.txt file) gives the next entry the first time pedestrian with id:2 appears: 

8.0400000e+02   2.0000000e+00   1.3017548e+01   0.0000000e+00   5.7825914e+00  -2.3244442e+00   0.0000000e+00  -7.6605938e-02

Where  1.3017548e+01 and 5.7825914e+00  are the x, y coordinates. So, my question is where is 13.64 (x of pedestrian 2) coming from? The same thing applies to many other positions. Thanks in advance.

**Comment by cschoeller** [comment]
Hey, I think you looked up the wrong file, obsmat.txt is the observation matrix of the camera, i.e. its calibration. You have to look up datasets/eth/test.txt in the S-GAN repo. There line 3 and 4 correspond to the entries in '3.json'. Hope that helps!

**Comment by risk-v** [comment]
Hi Christoph,

Thanks a million. Using the dataset from a different repo worked and I was able to replicate the results from your paper.

**Comment by cschoeller** [comment]
Glad to hear that! :)
